rerankers:
  FlagEmbedding:
    - name: BAAI/bge-reranker-v2-m3
      model_name_or_path: BAAI/bge-reranker-v2-m3
      cache_dir: ./models/cache/model
      use_fp16: true
      trust_remote_code: true
      device: cuda
      batch_size: 16
    - name: BAAI/bge-reranker-base
      model_name_or_path: BAAI/bge-reranker-base
      cache_dir: ./models/cache/model
      use_fp16: true
      trust_remote_code: true
      device: cuda
      batch_size: 16
